### ISSUE TITLE
vdpa: Incorrect implementation of get_iova_range()

### ISSUE THREAD

**Issue by sboeuf** [rust-vmm/vhost#106]
Hi @stefano-garzarella 
I think there's an error with the current implementation of `get_iova_range` as it uses the wrong ioctl: https://github.com/rust-vmm/vhost/blob/main/src/vhost_kern/vdpa.rs#L142

Could you confirm if this is an issue?

**Comment by stefano-garzarella** [comment]
Absolutely, we should use `VHOST_VDPA_GET_IOVA_RANGE`.
Thanks for reporting!

I was wondering why the test didn't fail, indeed, I didn't even write the test :-(, my bad!

Do you want to send a patch? Otherwise, I can do it.

**Comment by sboeuf** [comment]
> Absolutely, we should use `VHOST_VDPA_GET_IOVA_RANGE`. Thanks for reporting!

Sure :)

> 
> I was wondering why the test didn't fail, indeed, I didn't even write the test :-(, my bad!
> 
> Do you want to send a patch? Otherwise, I can do it.

If you have some free cycles, go ahead, otherwise I'll get to it later next week.

**Comment by stefano-garzarella** [comment]
> If you have some free cycles, go ahead, otherwise I'll get to it later next week.

I'll fix it ;-)
