### ISSUE TITLE
Release version 0.1.0 to crates.io

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/vhost#12]
There are several projects using this crate, it would be great to publish this crate to crates.io.

**Comment by andreeaflorescu** [comment]
@jiangliu the coverage on the crate is very low (~40%). We typically published the other crates with a coverage of 80-90%. Are you planning on adding more tests?

**Comment by jiangliu** [comment]
I'm going over the code again, and will help to add more test cases:)

**Comment by jiangliu** [comment]
@sboeuf @slp 
We are preparing for publishing to crates.io. 
The following PR should be merged before publishing:
https://github.com/rust-vmm/vhost/pull/24
https://github.com/rust-vmm/vhost/pull/26

Is there anymore tasks we need to handle before publishing?

**Comment by sboeuf** [comment]
@jiangliu
>Is there anymore tasks we need to handle before publishing?

Not that I can think of. Let's publish once we got #24 and #26 merged :)

**Comment by slp** [comment]
> Not that I can think of. Let's publish once we got #24 and #26 merged :)

I agree. We need #24, at least.

**Comment by slp** [comment]
@jiangliu How are going the plans for releasing it to crates.io? Which PRs must be merged before doing that?

**Comment by stefano-garzarella** [comment]
I'm closing this issue since we already released `0.1.0` on creates.io.
Feel free to reopen if it is wrong to close this.
