### ISSUE TITLE
Clarification of return type of `handle_event`

### ISSUE THREAD

**Issue by Ablu** [rust-vmm/vhost#144]
`VhostUserBackendMut::handle_event` has a bool return type that is not documented. Drilling into the code reveals that 
```
                // handle_event() returns true if an event is received from the exit event fd.
```
[1]

However, it looks like this is handled at [2]. Are there still valid use-cases where someone else should return a true there? Or shall we drop the bool from `VhostUserBackend` and `VhostUserBackendMut`?

@jiangliu: Maybe you can comment on this?

[1] https://github.com/rust-vmm/vhost/blame/40006d0b3981504320ae66e165c9fd36ce9cfb18/crates/vhost-user-backend/src/event_loop.rs#L196
[2] https://github.com/rust-vmm/vhost/blame/40006d0b3981504320ae66e165c9fd36ce9cfb18/crates/vhost-user-backend/src/event_loop.rs#L207

**Comment by stefano-garzarella** [comment]
Yeah, every time I'm confused about that return value. I think we should improve the documentation or drop the return value if not needed anymore.

@jiangliu WDYT?

**Comment by stefano-garzarella** [comment]
I just checked all the implementation of `handle_event` in https://github.com/rust-vmm/vhost and https://gitlab.com/virtio-fs/virtiofsd always return `Ok(false)` or an error.

And in https://github.com/rust-vmm/vhost/blob/5278cb549f2a01370fd081bc850b2e583aad7e2d/crates/vhost-user-backend/src/event_loop.rs#L196 we handle properly the `exit_event_fd`, so I think we can avoid returning a bool.

**Comment by stefano-garzarella** [comment]
I'm going to post a PR, we can discuss there.
