### ISSUE TITLE
Potential regression for vDPA support

### ISSUE THREAD

**Issue by likebreath** [rust-vmm/vhost#164]
With upgrading Cloud Hypervisor's dependencies of various rust-vmm crates [1], our CI reported the vDPA integration tests (that uses in-kernel vDPA device simulators) are failing with the latest release vhost v0.7.0 [2]. 

I found the breaking commit is 7e76859b3e272e64bd31cd0a63a8709c6efdfc4f, which essentially switches to use host virtual address (HVA) instead of guest physical address (GPA) with the ioctl `VHOST_SET_VRING_ADDR`. Considering the in-kernel vDPA device simulators were working fine with GPA, I wonder if this commit brings regressions to vDPA support?

[1] https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5451
[2] https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/blue/organizations/jenkins/cloud-hypervisor/detail/PR-5451/6/pipeline/169

/cc @sboeuf @rbradford

**Comment by sboeuf** [comment]
@stefano-garzarella do you know if the vdpa backend expects GPAs or HVAs from `VHOST_SET_VRING_ADDR`?

**Comment by stefano-garzarella** [comment]
@likebreath @sboeuf vdpa backend expects IOVA that the VMM should map with `dma_map`, so maybe adding an extra mapping could fix the issue, or we should override the `set_vring_addr` .

IIUC QEMU uses HVA for vhost devices and GPA for vdpa devices, because it already maps the entire guest memory, so in this way you don't need and extra maps.

I'm not sure about the extra mapping, since the address may collide.

**Comment by sboeuf** [comment]
Thanks @stefano-garzarella
IIUC, the problem is at the specification level (but there's no real specification for vhost unfortunately). It's wrong that `VHOST_SET_VRING_ADDR` expects different types of addresses depending on the backend (`vhost-net`/`vhost-vsock` vs `vdpa`).

Anyway, I agree that overriding `set_vring_addr()` implementation for `vdpa` is the best we can do here.

**Comment by stefano-garzarella** [comment]
> Thanks @stefano-garzarella IIUC, the problem is at the specification level (but there's no real specification for vhost unfortunately). It's wrong that `VHOST_SET_VRING_ADDR` expects different types of addresses depending on the backend (`vhost-net`/`vhost-vsock` vs `vdpa`).

Yep, I agree, but IIRC vhost supports both IOVA and HVA, while vhost-vdpa supports only IOVA.
In practice, they are a bit different, but as you said, vhost doesn't have a real spec.

> 
> Anyway, I agree that overriding `set_vring_addr()` implementation for `vdpa` is the best we can do here.

+1

**Comment by likebreath** [comment]
> > Thanks @stefano-garzarella IIUC, the problem is at the specification level (but there's no real specification for vhost unfortunately). It's wrong that `VHOST_SET_VRING_ADDR` expects different types of addresses depending on the backend (`vhost-net`/`vhost-vsock` vs `vdpa`).
> 
> Yep, I agree, but IIRC vhost supports both IOVA and HVA, while vhost-vdpa supports only IOVA. In practice, they are a bit different, but as you said, vhost doesn't have a real spec.
> 
> > Anyway, I agree that overriding `set_vring_addr()` implementation for `vdpa` is the best we can do here.
> 
> +1

@sboeuf @stefano-garzarella Thank you for the prompt response. I can send a PR for this later today if you haven't started.

**Comment by sboeuf** [comment]
> > > Thanks @stefano-garzarella IIUC, the problem is at the specification level (but there's no real specification for vhost unfortunately). It's wrong that `VHOST_SET_VRING_ADDR` expects different types of addresses depending on the backend (`vhost-net`/`vhost-vsock` vs `vdpa`).
> > 
> > 
> > Yep, I agree, but IIRC vhost supports both IOVA and HVA, while vhost-vdpa supports only IOVA. In practice, they are a bit different, but as you said, vhost doesn't have a real spec.
> > > Anyway, I agree that overriding `set_vring_addr()` implementation for `vdpa` is the best we can do here.
> > 
> > 
> > +1
> 
> @sboeuf @stefano-garzarella Thank you for the prompt response. I can send a PR for this later today if you haven't started.

No, it's all yours @likebreath !
