### ISSUE TITLE
Vhost crate point release for fixing vDPA regression

### ISSUE THREAD

**Issue by likebreath** [rust-vmm/vhost#166]
I wonder if the community is fine with cutting a new point release and publish it to crates.io to include the fix on vDPA regression (#165)? 

This would be very useful for Cloud Hypervisor to directly consume the released version of `vhost` crate and upgrade all other rust-vmm dependencies. Thank you.

/cc @stefano-garzarella @sboeuf

**Comment by sboeuf** [comment]
Sure :+1:

**Comment by stefano-garzarella** [comment]
I think so, but this week and next week (KVM Forum, DevConf.cz) will be very busy for me, so I can't do that for the next 2 weeks.

**Comment by likebreath** [comment]
> I think so, but this week and next week (KVM Forum, DevConf.cz) will be very busy for me, so I can't do that for the next 2 weeks.

Thank you for the heads-up. 

I'd like to help, but I think cutting release requires at least write access to the repo (for pushing tags)..

**Comment by stefano-garzarella** [comment]
Sorry about that, we will release #165 in the next release happening in #160 

Is that okay for you?

**Comment by stefano-garzarella** [comment]
`vhost v0.8.0` is just released with #165 included!
