### ISSUE TITLE
vhost-user-backend: Release new version  (fix GET_VRING_BASE behavior)

### ISSUE THREAD

**Issue by germag** [rust-vmm/vhost#169]
PR #161 doesn't reset the VQ after receiving a GET_VRING_BASE message.
(PR #154 it's also required, but it's already included in v0.9.0)

This fix is required to suspend/resume a VM with a vhot-user device, like virtiofsd:
https://gitlab.com/virtio-fs/virtiofsd/-/issues/110

**Comment by stefano-garzarella** [comment]
In #160 we are preparing a new release that will include also #161 ;-)

**Comment by stefano-garzarella** [comment]
`vhost-user-backend v0.10.0` is just released with #161 included!
