### ISSUE TITLE
Guest kernel hangs during boot while enabling vhost-backed device

### ISSUE THREAD

**Issue by spernsteiner** [rust-vmm/vhost#247]
When booting a Linux guest VM under QEMU with `vhost-device-gpio`, the kernel sometimes hangs during the boot process.  I believe this is due to a race condition between `vhost`'s handling of `SET_VRING_ENABLED` requests and `vhost-user-backend`'s handling of kick eventfd notifications.

The initial symptom I observed was the guest hanging indefinitely during boot.  Roughly half the time, the boot process would get stuck at this point:
```
[   10.971465] virtio-pci 0000:00:06.0: enabling device (0000 -> 0002)
```
`0000:00:06.0` is the `vhost-user-gpio-pci` device, backed by `vhost-device-gpio`.  This is running `qemu-system-aarch64` with KVM enabled on an aarch64 host.  The guest kernel is built with `CONFIG_GPIO_VIRTIO=y`, which means the virtio GPIO driver is built into the kernel and the GPIO device gets enabled early in the boot process.

I believe the bug is triggered when a notification on a vring's kick eventfd arrives before the `SET_VRING_ENABLED` request that enables that vring.  When a kick event arrives before the vring is enabled, some event handling is skipped (`VringEpollHandler::handle_event` skips the call to `self.backend.handle_event`), and enabling the vring later does not cause event handling to start.

To test this theory, I tried inserting `sleep` calls in two different places to force the kick and enable events to be processed in a certain order.  First, to force the kick to be processed first, I added a `sleep` just before processing `SET_VRING_ENABLED`:
```diff
--- a/vhost/src/vhost_user/backend_req_handler.rs
+++ b/vhost/src/vhost_user/backend_req_handler.rs
@@ -510,6 +510,8 @@ impl<S: VhostUserBackendReqHandler> BackendReqHandler<S> {
                 self.send_reply_message(&hdr, &msg)?;
             }
             Ok(FrontendReq::SET_VRING_ENABLE) => {
+                eprintln!("delaying enable");
+                std::thread::sleep(std::time::Duration::from_secs(1));
                 let msg = self.extract_request_body::<VhostUserVringState>(&hdr, size, &buf)?;
                 self.check_feature(VhostUserVirtioFeatures::PROTOCOL_FEATURES)?;
                 let enable = match msg.num {
```
Second, to force the enable to be processed first, I added a `sleep` just before processing epoll events (which include kick events and possibly others):
```diff
--- a/vhost-user-backend/src/event_loop.rs
+++ b/vhost-user-backend/src/event_loop.rs
@@ -170,6 +170,9 @@ where
                 }
             };

+            eprintln!("delaying kick");
+            std::thread::sleep(std::time::Duration::from_secs(1));
+
             for event in events.iter().take(num_events) {
                 let evset = match EventSet::from_bits(event.events) {
                     Some(evset) => evset,
```
(These patches should be applied to separate checkouts - applying both at once is not likely to do anything useful.)

I started the VM 10 times under each configuration and recorded how many times I saw it hang after `virtio-pci: enabling device`:

* No patch: failed 5/10 times
* Kick first: failed 10/10 times
* Enable first: failed 0/10 times

This supports the theory that the hang occurs when a kick event arrives before an enable.  Since the kick and enable events arrive on different fds and are delivered to different threads, I don't think the kernel guarantees any particular ordering for their delivery, and the bug occurs when the happen to arrive in the "wrong" order.

---

For easier testing, here is a way to reproduce these results on an x86_64 machine.  First, build a Linux kernel with `CONFIG_GPIO_VIRTIO=y`:

```sh
make defconfig
./scripts/config -e CONFIG_GPIOLIB
./scripts/config -e CONFIG_GPIO_VIRTIO
# Fill any remaining unset flags with defaults
make olddefconfig
# Build the kernel as normal
```

Then, run `vhost-device-gpio` and QEMU:

```sh
exec cargo run --release --features mock_gpio \
    --bin vhost-device-gpio -- \
    --socket-path gpio.socket \
    --device-list s8
```
```sh
exec qemu-system-x86_64 \
    -smp 2 -m 1024 \
    -cpu host -enable-kvm \
    -nographic \
    -kernel /path/to/vmlinuz \
    -append 'console=ttyS0' \
    -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/shm,share=on \
    -numa node,memdev=mem \
    -chardev socket,path=gpio.socket0,id=vgpio0 \
    -device vhost-user-gpio-pci,chardev=vgpio0,id=gpio0
```

With the "kick first" patch, this hangs at this point in the boot process:
```
[    0.182169] ACPI: button: Power Button [PWRF]
[    0.188289] ACPI: \_SB_.LNKD: Enabled at IRQ 11
```
With the "enable first" patch, it reaches the point of mounting the root filesystem, then panics (as expected, with no root device or initramfs provided to the VM):
```
[   10.147150] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
```

I ran the same sets of 10 test runs with this setup:

* No patch: failed 1/10 times
* Kick first: failed 10/10 times
* Enable first: failed 0/10 times

---

* QEMU version: 7.2
* Linux kernel version: 6.4 (aarch64 guest), 6.10 (x86_64 guest)
* vhost revision: 7554d06f (vhost package version 0.11.0)
* vhost-device revision: bef8b26b (vhost-device-gpio package version 0.1.0)

**Comment by stefano-garzarella** [comment]
This looks like more an issue on the VMM side, and it looks like similar to the problem fixed here in QEMU https://gitlab.com/qemu-project/qemu/-/commit/d7dc0682f5cb549ea9afdc418f95412e83cc5e8c

The fix was released with QEMU 8.2, so can you try that version or newer to see if it fixes this issue?
