### ISSUE TITLE
Check non-default feature code and tests in vhost-ci/clippy-x86

### ISSUE THREAD

**Issue by keiichiw** [rust-vmm/vhost#25]
The current `clippy-x86` builder in vhost-ci doesn't cover code for non-default features (e.g. `vhost-kern`, `vhost-user`, etc). So, we have some clippy errors there now, which will be fixed by #23.
To improve code quality, it would be nice if we can pass more flags in clippy there like `clippy --all-targets --all-features`.

**Comment by andreeaflorescu** [comment]
These should be added to a custom pipeline, similar to the other rust-vmm crates that have optional features.
Here is an example of a custom pipeline: https://github.com/rust-vmm/event-manager/blob/master/.buildkite/custom-pipeline.yml

The cargo clippy with more flags is already tracked to be added to all crates here: https://github.com/rust-vmm/rust-vmm-ci/issues/21

**Comment by keiichiw** [comment]
@jiangliu I think we need to update Buildkite as @andreeaflorescu  commented at https://github.com/rust-vmm/vhost/pull/26#issuecomment-789794527.
Can I ask you to do it?
