### ISSUE TITLE
Offset in VHOST_USER_GET_CONFIG/SET_CONFIG mismatch with qemu

### ISSUE THREAD

**Issue by dgreid** [rust-vmm/vhost#29]
The vhost crate considers offsets between the config offset and length as valid:
https://github.com/rust-vmm/vhost/blob/ee3e8722706c984b3dfe12d3a130e92101b78e8f/src/vhost_user/message.rs#L662
I believe the literal 0x100 is the config offset.

qemu, on the other hand, considers offsets valid from 0 to length, and assumes the offset uses CONFIG_OFFSET as a base.
See get_config in vhost-user.c, it sets config to offset 0 and length to max to cover the entire area.
https://source.codeaurora.org/quic/qemu/qemu/tree/hw/virtio/vhost-user.c?h=qemu.org/master#n2068

This mismatch causes the qemu GET_CONFIG message to be considered invalid by the vhost crate.

I didn't find anything in the spec indicating which is correct:
https://qemu.readthedocs.io/en/latest/interop/vhost-user.html

Deferring to qemu seems like the best thing for compatibility with qemu, but it might break existing users.

**Comment by jiangliu** [comment]
I would try my best to recall the reason for the " offset > 0x100" restriction:)

I think the key is how to interpret the vhost spec:
```
Virtio device config space
offset:  a 32-bit offset of virtio device’s configuration space
```
According to virtio spec:
```
Config 0x100+ RW
Configuration space: Device-specific configuration space starts at the offset 0x100 and is accessed with byte alignment. Its meaning and size depend on the device
and the driver.
```

The difference is caused by the way to interpret "configuration space". It will be super clear if the vhost spec is defined as
```
offset:  a 32-bit offset of virtio device’s device-specific configuration space
```

And I agree that the best way is to follow qemu's behavior for compatibility.

**Comment by jiangliu** [comment]
I have recently fixed some bug in processing SET_CONFIG/GET_CONFIG commands, that's a hint that it's not heavily used yet. So it should not be a big challenge to make this change. @dgreid

**Comment by dgreid** [comment]
Thanks @jiangliu, do you want to draft a patch, or should I?
