### ISSUE TITLE
vhost_user: Use File instead of RawFd in VhostUserSlaveReqHandler trait

### ISSUE THREAD

**Issue by keiichiw** [rust-vmm/vhost#37]
Currently, some methods in the `VhostUserSlaveReqHandler` trait, such as `set_vring_kick`, takes `RawFd`s as their arguments. However, this design doesn't allow a trait implementor to know whether the given FDs are valid and who its owner is. This means it cannot call `from_raw_fd()` for the given FD safely.

So, it'd be nice if the `VhostUserSlaveReqHandler` trait is updated to pass around `File`s instead of `RawFd`s. Then, the ownership of the underlying FD will become clearer.

**Comment by jiangliu** [comment]
The supposed usage pattern is:
1) the vhost master(say the vmm) owns the File object.
2) the vhost master send file descriptor to the vhost slave.
3) the unix domain socket send fds API will duplicate the fd into the vhost slave, so the slave could create a File from the received fd.
4) If the communication channel breaks, the master could redo 1-3 to build a new communication channel.
In other words, set_vring_kick() should not take ownership of the EventFd object, otherwise the vhost master must duplicate the EventFd object when calling set_vring_kick and friends.

**Comment by keiichiw** [comment]
Thanks for the explanation. Then, can we create a `File` from the duplicated FD in the slave and pass `&File` to `set_vring_kick()`? `&EventFd` is probably okay as well.

`RawFd` is less informative about ownership because it can be obtained by both `AsRawFd` and `IntoRawFd`.

**Comment by jiangliu** [comment]
> Thanks for the explanation. Then, can we create a `File` from the duplicated FD in the slave and pass `&File` to `set_vring_kick()`? `&EventFd` is probably okay as well.
> 
> `RawFd` is less informative about ownership because it can be obtained by both `AsRawFd` and `IntoRawFd`.

On the slave side, it owns the received fd, so it's legal to create a File object from the received fd and pass on the created File object.

**Comment by keiichiw** [comment]
> In other words, set_vring_kick() should not take ownership of the EventFd object

Hmm, it doesn't seem that `DummySlaveReqHandler` assume this because it closes kick_fd in the body of set_vring_kick()'s body [here](https://github.com/rust-vmm/vhost/blob/c4cd1d375e386069d0b781174de9f62ef41812e2/src/vhost_user/dummy_slave.rs#L143).

If set_vring_kick() doesn't take the ownership of the FD as you mentioned above, I think `struct SlaveReqHandler` has a responsibility of closing obsoleted FDs once the master redo 1-3, doesn't it?
Where should the FD be closed in the slave?

**Comment by jiangliu** [comment]
Sorry, I mis-read the "VhostUserSlaveReqHandler" and assume we are talking about the master side. For VhostUserSlaveReqHandler, it's a better design to take a File object instead of RawFd to explicitly transfer ownership.
