### ISSUE TITLE
Goal for the crate

### ISSUE THREAD

**Issue by sboeuf** [rust-vmm/vhost#4]
Looking for feedback and guidance here.
The README from this crate says:
```
A crate to implement the vHost ioctl interfaces and vHost-user protocol.
```
Do we really want to put together the vhost part that is about defining traits that can be used both for vhost and vhost-user devices, and the part about vhost-user protocol?
I think we could get the vhost-user-protocol living in its own crate since it could be reused by a vhost-user daemon. This would not force this daemon to pull the vhost/vhost-user traits code.

**Comment by jiangliu** [comment]
We have provided two feature flags to select vhost-kern and vhost-user modules.
And  with the landing of linux vDPA framework, we may add support of vDPA in future.

**Comment by jiangliu** [comment]
will add support of vDPA in future, so will keep current structure.
